# SDWAN 客户端配置
# 一行一个 key=value，# 开头为注释
# Windows: 放 exe 同目录
# Linux/macOS: 放 /etc/sdwan/iwan.conf

server=minieye.9966.org
username=your_username
password=your_password
port=10010
mtu=1436
encrypt=0
tunname=iwan1
routenet=192.168.0.0/16
